<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-LD88KNN" failures="1" tests="3" name="Test(failed)(failed)" time="0.169" errors="0" timestamp="2022-10-06T15:57:55 PDT">
  <testcase classname="depndsOnMethod.DependsOnMethod2" name="testcase" time="0.022"/>
  <testcase classname="depndsOnMethod.DependsOnMethod2" name="testCase2" time="0.009">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at depndsOnMethod.DependsOnMethod2.testCase2(DependsOnMethod2.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testCase2 -->
  <testcase classname="depndsOnMethod.DependsOnMethod3" name="testCase4" time="0.0">
    <skipped/>
  </testcase> <!-- testCase4 -->
  <testcase classname="depndsOnMethod.DependsOnMethod2" name="testCase1" time="0.0">
    <ignored/>
  </testcase> <!-- testCase1 -->
</testsuite> <!-- Test(failed)(failed) -->
